"use client";
import { FormEvent, useState } from "react";
import { CheckCircle2, Circle, Plus, Target, Trash2 } from "lucide-react";
import { UserGoal } from "@/lib/skillState";
interface NextGoalsProps { goals: UserGoal[]; onAddCustom: (title: string) => void; onToggle: (id: string) => void; onRemove: (id: string) => void; }
export default function NextGoals({ goals, onAddCustom, onToggle, onRemove }: NextGoalsProps) {
 const [title, setTitle] = useState(""); const submit = (event: FormEvent) => { event.preventDefault(); if (!title.trim()) return; onAddCustom(title.trim()); setTitle(""); };
 return <section className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm dark:border-[#282828] dark:bg-[#1c1c1c]"><div className="mb-3 flex items-center gap-2"><Target className="h-4 w-4 text-[#3ecf8e]" /><h2 className="text-sm font-semibold text-slate-900 dark:text-[#ededed]">Next Goals</h2></div><form onSubmit={submit} className="mb-3 flex gap-2"><input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Add a custom goal…" className="min-w-0 flex-1 rounded-lg border border-slate-200 bg-slate-50 px-3 py-2 text-xs outline-none focus:border-[#3ecf8e] dark:border-[#383838] dark:bg-[#161616]" /><button type="submit" className="inline-flex shrink-0 items-center gap-1 rounded-lg bg-[#3ecf8e] px-3 py-2 text-xs font-semibold text-[#042f1a]"><Plus className="h-3.5 w-3.5" />Add</button></form><div className="space-y-2">{goals.length === 0 ? <p className="rounded-lg border border-dashed border-slate-200 px-3 py-4 text-center text-xs text-slate-500 dark:border-[#383838] dark:text-zinc-400">No goals yet. Add one from a skill or create your own.</p> : goals.map((goal) => <div key={goal.id} className="flex items-start gap-2 rounded-lg border border-slate-100 bg-slate-50 px-3 py-2 dark:border-[#282828] dark:bg-[#161616]"><button type="button" onClick={() => onToggle(goal.id)} className="mt-0.5 shrink-0 text-[#3ecf8e]">{goal.completed ? <CheckCircle2 className="h-4 w-4" /> : <Circle className="h-4 w-4" />}</button><span className={`min-w-0 flex-1 break-words text-xs ${goal.completed ? "text-slate-400 line-through dark:text-zinc-500" : "text-slate-700 dark:text-zinc-300"}`}>{goal.title}</span><button type="button" onClick={() => onRemove(goal.id)} aria-label={`Remove ${goal.title}`} className="shrink-0 text-slate-400 hover:text-rose-500"><Trash2 className="h-3.5 w-3.5" /></button></div>)}</div></section>;
}
