"use client";

import { useMemo, useState } from "react";
import { Check, ChevronDown, ChevronRight, Lock } from "lucide-react";
import { SkillRank } from "@/lib/tierConfig";

export interface SkillTreeNode { id: string; skillName: string; parentId: string | null; rankTier?: SkillRank; category?: string; completed?: boolean; locked?: boolean; }
export interface SkillNodeTreeProps { nodes: SkillTreeNode[]; onNodeClick?: (id: string) => void; selectedId?: string; }
type TreeNode = SkillTreeNode & { children: TreeNode[] };

function buildTree(nodes: SkillTreeNode[]) { const map = new Map(nodes.map((node) => [node.id, { ...node, children: [] as TreeNode[] }])); const roots: TreeNode[] = []; map.forEach((node) => node.parentId && map.has(node.parentId) ? map.get(node.parentId)!.children.push(node) : roots.push(node)); return roots; }

function SkillRow({ node, onNodeClick, selectedId }: { node: TreeNode; onNodeClick?: (id: string) => void; selectedId?: string }) {
  const [expanded, setExpanded] = useState(true); const hasChildren = node.children.length > 0;
  return <div><div className={`flex min-w-0 items-center gap-2 rounded-lg px-2 py-2 transition-colors ${selectedId === node.id ? "bg-[#3ecf8e]/10 ring-1 ring-[#3ecf8e]/40" : "hover:bg-slate-50 dark:hover:bg-[#232323]"}`}>
    {hasChildren ? <button type="button" aria-label={`${expanded ? "Collapse" : "Expand"} ${node.skillName}`} onClick={() => setExpanded((value) => !value)} className="shrink-0 text-slate-400 hover:text-slate-700 dark:hover:text-zinc-200">{expanded ? <ChevronDown className="h-4 w-4" /> : <ChevronRight className="h-4 w-4" />}</button> : <span className="w-4 shrink-0" />}
    <button type="button" onClick={() => onNodeClick?.(node.id)} className="flex min-w-0 flex-1 items-center gap-2 text-left"><span className={`flex h-6 w-6 shrink-0 items-center justify-center rounded-full border ${node.completed ? "border-[#3ecf8e] bg-[#3ecf8e]/20 shadow-[0_0_10px_rgba(62,207,142,0.45)]" : node.locked ? "border-slate-300 bg-slate-100 text-slate-400 dark:border-zinc-700 dark:bg-[#161616]" : "border-amber-400/60 bg-amber-400/10"}`}>{node.completed ? <Check className="h-3.5 w-3.5 text-[#21875c] dark:text-[#3ecf8e]" /> : node.locked ? <Lock className="h-3 w-3" /> : <span className="h-2 w-2 rounded-full bg-amber-400" />}</span><span className={`min-w-0 flex-1 break-words text-xs font-medium ${node.locked ? "text-slate-500 dark:text-zinc-500" : "text-slate-800 dark:text-zinc-200"}`}>{node.skillName}</span><span className={`shrink-0 rounded px-1.5 py-0.5 text-[9px] font-semibold ${node.completed ? "bg-[#3ecf8e]/10 text-[#21875c] dark:text-[#3ecf8e]" : node.locked ? "bg-slate-100 text-slate-400 dark:bg-[#282828] dark:text-zinc-500" : "bg-amber-400/10 text-amber-600 dark:text-amber-300"}`}>{node.completed ? "Completed" : node.locked ? "Locked" : "Incomplete"}</span></button>
  </div>{hasChildren && expanded && <div className="ml-4 border-l border-slate-200 pl-2 dark:border-[#282828]">{node.children.map((child) => <SkillRow key={child.id} node={child} onNodeClick={onNodeClick} selectedId={selectedId} />)}</div>}</div>;
}

function CategoryBranch({ category, nodes, onNodeClick, selectedId }: { category: string; nodes: SkillTreeNode[]; onNodeClick?: (id: string) => void; selectedId?: string }) { const [expanded, setExpanded] = useState(false); const tree = useMemo(() => buildTree(nodes), [nodes]); const done = nodes.filter((node) => node.completed).length; return <section className="rounded-lg border border-slate-100 bg-slate-50/60 dark:border-[#282828] dark:bg-[#161616]"><button type="button" onClick={() => setExpanded((value) => !value)} className="flex w-full items-center gap-2 px-3 py-3 text-left"><span className="text-slate-400">{expanded ? <ChevronDown className="h-4 w-4" /> : <ChevronRight className="h-4 w-4" />}</span><span className="min-w-0 flex-1 break-words text-xs font-bold uppercase tracking-wide text-slate-700 dark:text-zinc-200">{category}</span><span className="shrink-0 text-[10px] text-slate-400 dark:text-zinc-500">{done}/{nodes.length} done</span></button>{expanded && <div className="border-t border-slate-100 p-2 dark:border-[#282828]">{tree.map((node) => <SkillRow key={node.id} node={node} onNodeClick={onNodeClick} selectedId={selectedId} />)}</div>}</section>; }

export default function SkillNodeTree({ nodes, onNodeClick, selectedId }: SkillNodeTreeProps) { const categories = useMemo(() => Object.entries(nodes.reduce<Record<string, SkillTreeNode[]>>((groups, node) => { (groups[node.category || "Uncategorized"] ||= []).push(node); return groups; }, {})), [nodes]); const done = nodes.filter((node) => node.completed).length; return <section className="w-full rounded-xl border border-slate-200 bg-white p-4 shadow-sm dark:border-[#282828] dark:bg-[#1c1c1c]"><header className="mb-3 flex flex-wrap items-start justify-between gap-2 border-b border-slate-100 pb-3 dark:border-[#282828]"><div><h2 className="text-sm font-semibold text-slate-900 dark:text-[#ededed]">All Skills Tree</h2><p className="mt-1 text-xs text-slate-500 dark:text-zinc-400">Open a category, then select a skill to view its details.</p></div><span className="rounded-full bg-[#3ecf8e]/10 px-2.5 py-1 text-xs font-semibold text-[#21875c] dark:text-[#3ecf8e]">{done}/{nodes.length} completed</span></header><div className="max-h-[38rem] space-y-2 overflow-y-auto pr-1">{categories.map(([category, categoryNodes]) => <CategoryBranch key={category} category={category} nodes={categoryNodes} onNodeClick={onNodeClick} selectedId={selectedId} />)}</div></section>; }
